#!
mv apply_application_category.php apply_application_category.php.closed
mv apply_basetechnology_category.php apply_basetechnology_category.php.closed
mv apply_dataset_category.php apply_dataset_category.php.closed
mv apply_idea_category.php apply_idea_category.php.closed
mv apply_visualization_category.php apply_visualization_category.php.closed
mv modify_application_status.php modify_application_status.php.closed
mv modify_basetechnology_status.php modify_basetechnology_status.php.closed
mv modify_dataset_status.php modify_dataset_status.php.closed
mv modify_idea_status.php modify_idea_status.php.closed
mv modify_visualization_status.php modify_visualization_status.php.closed
mv registered_application.php registered_application.php.closed
mv registered_basetechnology.php  registered_basetechnology.php.closed
mv registered_dataset.php registered_dataset.php.closed
mv registered_idea.php  registered_idea.php.closed
mv registered_visualization.php  registered_visualization.php.closed
