USE `lod_db`;
DROP TABLE IF EXISTS `application_2013`;
CREATE TABLE `application_2013` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(30) COLLATE utf8_unicode_ci NOT NULL,
  `affiliation` varchar(80) COLLATE utf8_unicode_ci NOT NULL,
  `affiliation_anonymous` tinyint(1) NOT NULL,
  `is_student` tinyint(1) DEFAULT NULL,
  `email` varchar(80) COLLATE utf8_unicode_ci NOT NULL,
  `email_anonymous` tinyint(1) NOT NULL,
  `set_mailinglist` tinyint(1) NOT NULL,
  `application_name` varchar(80) COLLATE utf8_unicode_ci NOT NULL,
  `url` varchar(500) COLLATE utf8_unicode_ci NOT NULL,
  `abstract` varchar(110) COLLATE utf8_unicode_ci NOT NULL,
  `description` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `icon_filename` varchar(500) COLLATE utf8_unicode_ci  DEFAULT NULL,
  `used_dataset_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `copyright` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `hashed_password` varchar(40) COLLATE utf8_unicode_ci NOT NULL,
  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `license` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_dataset_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_idea_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_application_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_visualization_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_basetechnology_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `is_closed` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

DROP TABLE IF EXISTS `application_input_2013`;
CREATE TABLE `application_input_2013` (
  `master_id` int(11) NOT NULL,
  `name` varchar(30) COLLATE utf8_unicode_ci NOT NULL,
  `affiliation` varchar(80) COLLATE utf8_unicode_ci NOT NULL,
  `affiliation_anonymous` tinyint(1) NOT NULL,
  `is_student` tinyint(1) DEFAULT NULL,
  `email` varchar(80) COLLATE utf8_unicode_ci NOT NULL,
  `email_anonymous` tinyint(1) NOT NULL,
  `set_mailinglist` tinyint(1) NOT NULL,
  `application_name` varchar(80) COLLATE utf8_unicode_ci NOT NULL,
  `url` varchar(500) COLLATE utf8_unicode_ci NOT NULL,
  `abstract` text COLLATE utf8_unicode_ci NOT NULL,
  `description` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `icon_filename` varchar(500) COLLATE utf8_unicode_ci  DEFAULT NULL,
  `used_dataset_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `copyright` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `license` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_dataset_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_idea_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_application_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_visualization_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_basetechnology_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `is_closed` tinyint(1) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

DROP TABLE IF EXISTS `dataset_2013`;
CREATE TABLE `dataset_2013` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(30) COLLATE utf8_unicode_ci NOT NULL,
  `affiliation` varchar(80) COLLATE utf8_unicode_ci NOT NULL,
  `affiliation_anonymous` tinyint(1) NOT NULL,
  `is_student` tinyint(1) DEFAULT NULL,
  `email` varchar(80) COLLATE utf8_unicode_ci NOT NULL,
  `email_anonymous` tinyint(1) NOT NULL,
  `set_mailinglist` tinyint(1) NOT NULL,
  `dataset_name` varchar(80) COLLATE utf8_unicode_ci NOT NULL,
  `url` varchar(500) COLLATE utf8_unicode_ci NOT NULL,
  `abstract` text COLLATE utf8_unicode_ci NOT NULL,
  `description` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `icon_filename` varchar(500) COLLATE utf8_unicode_ci  DEFAULT NULL,
  `request` text COLLATE utf8_unicode_ci,
  `copyright` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `star` int(11) DEFAULT NULL,
  `hashed_password` varchar(40) COLLATE utf8_unicode_ci NOT NULL,
  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `creator` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_dataset_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_idea_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_application_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_visualization_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_basetechnology_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `is_closed` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

DROP TABLE IF EXISTS `dataset_input_2013`;
CREATE TABLE `dataset_input_2013` (
  `master_id` int(11) NOT NULL,
  `name` varchar(30) COLLATE utf8_unicode_ci NOT NULL,
  `affiliation` varchar(80) COLLATE utf8_unicode_ci NOT NULL,
  `affiliation_anonymous` tinyint(1) NOT NULL,
  `is_student` tinyint(1) DEFAULT NULL,
  `email` varchar(80) COLLATE utf8_unicode_ci NOT NULL,
  `email_anonymous` tinyint(1) NOT NULL,
  `set_mailinglist` tinyint(1) NOT NULL,
  `dataset_name` varchar(80) COLLATE utf8_unicode_ci NOT NULL,
  `url` varchar(500) COLLATE utf8_unicode_ci NOT NULL,
  `abstract` text COLLATE utf8_unicode_ci NOT NULL,
  `description` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `icon_filename` varchar(500) COLLATE utf8_unicode_ci  DEFAULT NULL,
  `request` text COLLATE utf8_unicode_ci,
  `copyright` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `creator` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_dataset_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_idea_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_application_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_visualization_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_basetechnology_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `is_closed` tinyint(1) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

DROP TABLE IF EXISTS `idea_2013`;
CREATE TABLE `idea_2013` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(30) COLLATE utf8_unicode_ci NOT NULL,
  `affiliation` varchar(80) COLLATE utf8_unicode_ci NOT NULL,
  `affiliation_anonymous` tinyint(1) NOT NULL,
  `is_student` tinyint(1) DEFAULT NULL,
  `email` varchar(80) COLLATE utf8_unicode_ci NOT NULL,
  `email_anonymous` tinyint(1) NOT NULL,
  `set_mailinglist` tinyint(1) NOT NULL,
  `idea_name` varchar(80) COLLATE utf8_unicode_ci NOT NULL,
  `open` tinyint(1) DEFAULT NULL,
  `abstract` text COLLATE utf8_unicode_ci NOT NULL,
  `description` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `icon_filename` varchar(500) COLLATE utf8_unicode_ci  DEFAULT NULL,
  `type` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `url` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `original_filename` varchar(500) COLLATE utf8_unicode_ci  DEFAULT NULL,
  `disclosed` tinyint(1) NOT NULL DEFAULT '0',
  `hashed_password` varchar(40) COLLATE utf8_unicode_ci NOT NULL,
  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `related_dataset_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_idea_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_application_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_visualization_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_basetechnology_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `is_closed` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

DROP TABLE IF EXISTS `idea_input_2013`;
CREATE TABLE `idea_input_2013` (
  `master_id` int(11) NOT NULL,
  `name` varchar(30) COLLATE utf8_unicode_ci NOT NULL,
  `affiliation` varchar(80) COLLATE utf8_unicode_ci NOT NULL,
  `affiliation_anonymous` tinyint(1) NOT NULL,
  `is_student` tinyint(1) DEFAULT NULL,
  `email` varchar(80) COLLATE utf8_unicode_ci NOT NULL,
  `email_anonymous` tinyint(1) NOT NULL,
  `set_mailinglist` tinyint(1) NOT NULL,
  `idea_name` varchar(80) COLLATE utf8_unicode_ci NOT NULL,
  `open` tinyint(1) DEFAULT NULL,
  `abstract` text COLLATE utf8_unicode_ci NOT NULL,
  `description` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `icon_filename` varchar(500) COLLATE utf8_unicode_ci  DEFAULT NULL,
  `type` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `url` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `original_filename` varchar(500) COLLATE utf8_unicode_ci  DEFAULT NULL,
  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `related_dataset_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_idea_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_application_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_visualization_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_basetechnology_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `is_closed` tinyint(1) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

DROP TABLE IF EXISTS `visualization_2013`;
CREATE TABLE `visualization_2013` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(80) COLLATE utf8_unicode_ci NOT NULL,
  `affiliation` varchar(80) COLLATE utf8_unicode_ci NOT NULL,
  `affiliation_anonymous` tinyint(1) NOT NULL,
  `is_student` tinyint(1) DEFAULT NULL,
  `email` varchar(80) COLLATE utf8_unicode_ci NOT NULL,
  `email_anonymous` tinyint(1) NOT NULL,
  `set_mailinglist` tinyint(1) NOT NULL,
  `visualization_name` varchar(80) COLLATE utf8_unicode_ci NOT NULL,
  `abstract` text COLLATE utf8_unicode_ci NOT NULL,
  `description` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `icon_filename` varchar(500) COLLATE utf8_unicode_ci  DEFAULT NULL,
  `url` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `copyright` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `hashed_password` varchar(40) COLLATE utf8_unicode_ci NOT NULL,
  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `license` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `type` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `used_dataset_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_dataset_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_idea_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_application_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_visualization_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_basetechnology_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `is_closed` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

DROP TABLE IF EXISTS `visualization_input_2013`;
CREATE TABLE `visualization_input_2013` (
  `master_id` int(11) NOT NULL,
  `name` varchar(30) COLLATE utf8_unicode_ci NOT NULL,
  `affiliation` varchar(80) COLLATE utf8_unicode_ci NOT NULL,
  `affiliation_anonymous` tinyint(1) NOT NULL,
  `is_student` tinyint(1) DEFAULT NULL,
  `email` varchar(80) COLLATE utf8_unicode_ci NOT NULL,
  `email_anonymous` tinyint(1) NOT NULL,
  `set_mailinglist` tinyint(1) NOT NULL,
  `visualization_name` varchar(80) COLLATE utf8_unicode_ci NOT NULL,
  `abstract` text COLLATE utf8_unicode_ci NOT NULL,
  `description` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `icon_filename` varchar(500) COLLATE utf8_unicode_ci  DEFAULT NULL,
  `copyright` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `hashed_password` varchar(40) COLLATE utf8_unicode_ci NOT NULL,
  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `url` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `original_filename` varchar(500) COLLATE utf8_unicode_ci  DEFAULT NULL,
  `license` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `type` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `used_dataset_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_dataset_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_idea_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_application_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_visualization_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_basetechnology_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `is_closed` tinyint(1) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

DROP TABLE IF EXISTS `basetechnology_2013`;
CREATE TABLE `basetechnology_2013` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(80) COLLATE utf8_unicode_ci NOT NULL,
  `affiliation` varchar(80) COLLATE utf8_unicode_ci NOT NULL,
  `affiliation_anonymous` tinyint(1) NOT NULL,
  `is_student` tinyint(1) DEFAULT NULL,
  `email` varchar(80) COLLATE utf8_unicode_ci NOT NULL,
  `email_anonymous` tinyint(1) NOT NULL,
  `set_mailinglist` tinyint(1) NOT NULL,
  `basetechnology_name` varchar(80) COLLATE utf8_unicode_ci NOT NULL,
  `abstract` text COLLATE utf8_unicode_ci NOT NULL,
  `description` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `icon_filename` varchar(500) COLLATE utf8_unicode_ci  DEFAULT NULL,
  `url` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `original_filename` varchar(500) COLLATE utf8_unicode_ci  DEFAULT NULL,
  `copyright` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `hashed_password` varchar(40) COLLATE utf8_unicode_ci NOT NULL,
  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `license` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_dataset_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_idea_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_application_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_visualization_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_basetechnology_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `is_closed` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

DROP TABLE IF EXISTS `basetechnology_input_2013`;
CREATE TABLE `basetechnology_input_2013` (
  `master_id` int(11) NOT NULL,
  `name` varchar(80) COLLATE utf8_unicode_ci NOT NULL,
  `affiliation` varchar(80) COLLATE utf8_unicode_ci NOT NULL,
  `affiliation_anonymous` tinyint(1) NOT NULL,
  `is_student` tinyint(1) DEFAULT NULL,
  `email` varchar(80) COLLATE utf8_unicode_ci NOT NULL,
  `email_anonymous` tinyint(1) NOT NULL,
  `set_mailinglist` tinyint(1) NOT NULL,
  `basetechnology_name` varchar(80) COLLATE utf8_unicode_ci NOT NULL,
  `abstract` text COLLATE utf8_unicode_ci NOT NULL,
  `description` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `icon_filename` varchar(500) COLLATE utf8_unicode_ci  DEFAULT NULL,
  `url` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `copyright` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `hashed_password` varchar(40) COLLATE utf8_unicode_ci NOT NULL,
  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `license` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_dataset_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_idea_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_application_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_visualization_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `related_basetechnology_ids` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `is_closed` tinyint(1) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

